# Generated by Django 6.0 on 2026-01-01 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('capture_date', models.DateField()),
                ('original_image', models.ImageField(upload_to='photos/original/')),
                ('compressed_image', models.ImageField(upload_to='photos/compressed/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotosStore.user')),
            ],
            options={
                'db_table': 'photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
