# Generated by Django 6.0 on 2026-01-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhotosStore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
    ]
